learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines the URL pattern for the learning logs"""

from django.urls import path
from . import views


app_name = 'learning_logs'

urlpatterns = [
    # home page
    path('', views.index, name='index'),
    # topics page
    path('topics/', views.topics, name='topics'),
    # a single topic page with the associated entries
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # create new topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    # create a new entry page
    path('new_entry/<int:topic_id>', views.new_entry, name='new_entry'),
    # edit a previous entry
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""defines urls for the user app"""
from django.urls import include, path
from . import views


app_name = 'users'
urlpatterns = [
    # include default django auth
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Topic(models.Model):
    """topic the user is currently learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """returns the model in a string format"""
        return self.text


class Entry(models.Model):
    """entries based on what was learnt about a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        """extra information on how to handle the model"""
        verbose_name_plural = 'entries'

    def __str__(self):
        """display the model in a string format"""
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from .forms import TopicForm, EntryForm
from .models import Topic, Entry


# Create your views here.
def index(request):
    """The main homepage"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """show all the topics created"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """show a single topic and the associated entries"""
    topic = get_object_or_404(Topic, id=topic_id)
    # verifies if the topic belongs to the current user
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """Add new topic"""
    if request.method != 'POST':
        # create blank form
        form = TopicForm()
    else:
        # validate data in filled form and pass into database
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    # display blank/invalid form
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry to a topic"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # create blank form
        form = EntryForm()
    else:
        # validate, and add to database
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            # link the topic to the entry
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    # display blank/invalid forms
    context = {'form': form, 'topic': topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """edit existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # verifies if the entry belongs to the current user
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # fill the form with the previous entry data
        form = EntryForm(instance=entry)
    else:
        # update the form with the new data
        form = EntryForm(instance=entry, data=request.POST)
        # validate and save into database
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic.id)

    # display form to edit or if form is invalid
    context = {'form': form, 'topic': topic, 'entry': entry}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


# Create your views here.
def register(request):
    """register a new user"""
    # if not a post request then a get
    if request.method != 'POST':
        # create an empty form
        form = UserCreationForm()
    else:
        # fill the form with user data inputs
        form = UserCreationForm(data=request.POST)
        # save the data into the database, login the user and redirect to the homepage
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    # displays the empty/invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">create an account</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main class="container" role="main">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
  <h2>Edit entry</h2>
{% endblock page_header %}
{% block content %}
  <p>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Track Your Learning</h1>
        <p class="lead">
            Make a personalized learning log, that includes a list of any topics you are learning about
            with a summary of what you learned for a particular day
        </p>
        <a class="btn-lg btn btn-primary" href="{% url 'users:register' %}">Begin learning today! &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
    <h2>Add a new entry</h2>
{% endblock page_header%}
{% block content %}
  <p>Topic: <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add Entry</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block page_header %}
    <h2>Add a new Topic</h2>
{% endblock page_header %}
{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="POST" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <h3>Topic: {{ topic }}</h3>
{% endblock page_header %}
{% block content %}
    <p><a href="{% url 'learning_logs:new_entry' topic.id %}">Add a new entry</a></p>
    {% for entry in entries %}
        <div class="mb-3 card">
            <h4 class="card-header">
                {{ entry.date_added|date:"N j, Y" }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries</p>
    {% endfor %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a></h3>
            </li>
        {% empty %}
            <li>
                <h3>There are no topics created</h3>
            </li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new Topic</a></h3>
{% endblock content %}